version: "3"
services:
  dind:
    image: docker:stable-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
    working_dir: /workspace
    volumes:
      - ${PWD}:${PWD}
      - /tmp:/tmp
    command: dockerd-entrypoint.sh
  app:
    image: suecharo/sapporo-service:1.0.2
    container_name: sapporo
    volumes:
      - /tmp:/tmp
      - ${PWD}:${PWD}
    environment:
      - DOCKER_HOST=tcp://dind:2375/
      - SAPPORO_HOST=0.0.0.0
      - SAPPORO_PORT=8080
      - SAPPORO_DEBUG=False
      - SAPPORO_RUN_DIR=${PWD}/run
      - SAPPORO_GET_RUNS=True
      - SAPPORO_RUN_ONLY_REGISTERED_WORKFLOWS=False
      - SAPPORO_ACCESS_CONTROL_ALLOW_ORIGIN=*
    ports:
      - 8080:8080
    restart: always
    working_dir: ${PWD}
    command: ["sapporo"]
    depends_on:
      - "dind"
