version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sapporo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - ${PWD}:${PWD}
    environment:
      - SAPPORO_HOST=0.0.0.0
      - SAPPORO_PORT=8080
      - SAPPORO_DEBUG=True
    ports:
      - 8080:8080
    restart: always
    working_dir: ${PWD}
    command: ["/bin/bash", "./entrypoint.dev.sh"]
