version: "3"
services:
  app:
    image: suecharo/sapporo-service:v0.4.2
    container_name: sapporo-service-app-dev
    restart: always
    volumes:
      - /tmp:/tmp
      - /usr/bin/docker:/usr/bin/docker
      - /var/lib/docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/../etc:${PWD}/../etc
      - ${PWD}/../log/app:${PWD}/../log/app
      - ${PWD}/../run:${PWD}/../run
      - ${PWD}/../run/cache:/.cache
      - ${PWD}/../service-info.yml:${PWD}/../service-info.yml
      - ${PWD}/../src:${PWD}/../src
      - ${PWD}/../workflow-info.yml:${PWD}/../workflow-info.yml
    environment:
      - DEBUG=${SAPPORO_SERVICE_DEBUG:-True} # Flask debug mode
      - GET_RUNS=${SAPPORO_SERVICE_GET_RUNS:-True}
      - TOKEN_AUTH=${SAPPORO_SERVICE_TOKEN_AUTH:-False}
      - LOG_LEVEL=${SAPPORO_SERVICE_LOG_LEVEL:-DEBUG} # DEBUG or INFO
    user: ${UID:-0}:${DOCKER_GID:-999} # Docker group
    command: ["/usr/local/bin/python3", "${PWD}/../src/run.py"]
    working_dir: ${PWD}/..
    networks:
      - sapporo
    ports:
      - ${SAPPORO_SERVICE_PORT:-1122}:8080
networks:
  sapporo:
    external:
      name: sapporo-network
