version: "3.7"
services:
  dind:
    image: docker:stable-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
    working_dir: /workspace
    volumes:
      - ..:/workspace
      - /tmp:/tmp
    command: dockerd-entrypoint.sh
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - DOCKER_HOST=tcp://dind:2375/
      - SAPPORO_HOST=0.0.0.0
      - SAPPORO_PORT=8080
      - SAPPORO_DEBUG=True
      - SAPPORO_RUN_DIR=/workspace/run
      - SAPPORO_GET_RUNS=True
      - SAPPORO_RUN_ONLY_REGISTERED_WORKFLOWS=False
      - SAPPORO_ACCESS_CONTROL_ALLOW_ORIGIN
    working_dir: /workspace
    volumes:
      - ..:/workspace
      - /tmp:/tmp
    command: sleep infinity
    depends_on:
      - "dind"
