name: mypy

on: [push, pull_request, workflow_dispatch]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --progress-bar off -U pip setuptools wheel
          pip install --no-cache-dir --progress-bar off -U .[tests]
      - name: Check with mypy
        run: |
          bash ./tests/lint_and_style_check/mypy.sh
