name: upload_pypi

on:
  release:
    types:
      - published
  workflow_dispatch: {}

jobs:
  upload_pypi:
    if: github.repository == "ddbj/SAPPORO-service"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --progress-bar off -U pip setuptools wheel
          python -m pip install twine
      - name: Build a tar ball
        run: |
          python setup.py sdist
          python setup.py bdist_wheel
      - name: Verify the distributions
        run: twine check dist/*
      - name: Publish distribution to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
